modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/TehStoneMan/BetterStorageToo/issues"
[[mods]]
modId="betterstorage"
version="1.14.4-4.0.0.1"
displayName="BetterStorageToo"
updateJSONURL="http://tehstoneman.github.io/betterstorage.json"
displayURL="http://minecraft.curseforge.com/projects/betterstoragetoo"
authors="TehStoneMan, copygirl, Vic Nightfall"
description='''Adds more storage related blocks and items to the game.'''